
version: 2

models:
  - name: stg_Customer
    description: "Stage model for the customers table"
    columns:
      - name: CustomerId
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: CreationDate
        description: "The Date in which the customer was created"
      - name: region
        description: "The Region of the where customer is located"
        tests:
          - not_null
      - name: Gender
        description: "Gender of the customer"
        tests:
          - accepted_values:
              values: ['Male', 'Female', 'Other']

  - name: stg_Status
    description: "Stage model for the status table"
    columns:
      - name: StatusId
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: StatusName
        description: "The name of the status"
        tests:
          - not_null

  - name: stg_Orders
    description: "Stage model for the orders table"
    columns:
      - name: OrderId
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: CustomerId
        description: "The foreign key for customer table"
        tests:
          - not_null
      - name: OrderCreationDate
        description: "The date in which the order was Created"
        tests:
          - not_null
      - name: StatusId
        description: "The foreign key for Status table"
        tests:
          - not_null

  - name: stg_Products
    description: "Stage model for the products table"
    columns:
      - name: ProductId
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: ProductName
        description: "Name of the product"
        tests:
          - not_null
      - name: CategoryId
        description: "The foreign key for category table"
        tests:
          - not_null
      - name: BrandId
        description: "The foreign key for brand table"
        tests:
          - not_null
      - name: price
        description: "The price of the product"
        tests:
          - not_null
      - name: ProductCreationDate
        description: "The date in which the product was created"
        tests:
          - not_null

  - name: stg_WebTraffic
    description: "Stage model for the Web traffic table"
    columns:
      - name: VisitId
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: VisitTimestamp
        description: "The timestamp of the visit"
        tests:
          - not_null
      - name: Page
        description: "the page that was visited"
        tests:
          - not_null
      - name: SessionId
        description: "The session id of the visit"
        tests:
          - not_null
      - name: CustomerId
        description: "The foreign key for customer table"
        tests:
          - not_null
      - name: ReferralSource
        description: "The source from which the customer was referred"
        tests:
          - not_null

  - name: stg_Order_Items
    description: "Stage model for the order item table"
    columns:
      - name: OrderItemId
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: OrderId
        description: "The foreign key for order table"
        tests:
          - not_null
      - name: ProductId
        description: "the foreign key for product table"
        tests:
          - not_null
      - name: Quantity
        description: "the quantity of the product"
        tests:
          - not_null
      - name: Price
        description: "the price of the product"
        tests:
          - not_null